blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig
app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view_post'),
    path('create', BlogCreateView.as_view(), name='create_post'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update_post'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete_post'),

]

conf/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mailing
import users
from conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.views import MailinListView, MessageListView, MessageCreateView, MessageDeleteView, \
    MessageUpdateView, MessageDetailView, MailingCreateView, MailingDeleteView, MailingUpdateView, MailingDetailView, \
    LogListListView, ClientListView, ClientCreateView, ClientDeleteView, ClientUpdateView, ClientDetailView, \
    RedactMailingClientsListView, add_client_to_mailinglist, \
    delete_client_from_mailinglist, delete_all_clients_from_mailinglist, add_all_clients_to_mailinglist, \
    change_mailing_is_active, main_page
from mailing.apps import MailingConfig

app_name = MailingConfig.name


urlpatterns = [
    path('mailing_list', cache_page(60)(MailinListView.as_view()), name='mailing_list'),
    path('create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('delete_mailing/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('update_mailing/<int:pk>/', MailingUpdateView.as_view(), name='update_mailing'),
    path('detail_mailing/<int:pk>/', MailingDetailView.as_view(), name='detail_mailing'),
    path('change_mailing_is_active/<int:pk>/<act>/', change_mailing_is_active, name='change_mailing_is_active'),

    path('messages_list/', cache_page(60)(MessageListView.as_view()), name='messages_list'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),
    path('update_message/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('detail_message/<int:pk>/', MessageDetailView.as_view(), name='detail_message'),

    path('loglist_list/', cache_page(60)(LogListListView.as_view()), name='loglist_list'),

    path('clients_list/', ClientListView.as_view(), name='clients_list'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('detail_client/<int:pk>/', ClientDetailView.as_view(), name='detail_client'),
    
    path('redact_mailing_clients/<int:pk>/', RedactMailingClientsListView.as_view(), name='redact_mailing_clients'),
    path('add_client_to_mailinglist/<int:pk_client>/<int:pk_mailindmodel>/', add_client_to_mailinglist, name='add_client_to_mailinglist'),
    path('delete_client_to_mailinglist/<int:pk_client>/<int:pk_mailindmodel>/', delete_client_from_mailinglist, name='delete_client_to_mailinglist'),
    path('delete_all_clients_from_mailinglist/<int:pk_mailindmodel>/', delete_all_clients_from_mailinglist, name='delete_all_clients_from_mailinglist'),
    path('add_all_clients_to_mailinglist/<int:pk_mailindmodel>/', add_all_clients_to_mailinglist, name='add_all_clients_to_mailinglist'),

    path('', main_page, name='main_page'),

]

mailing/models.py
from django.db import models
from django.utils import timezone

from conf import settings

NULLABLE = {'blank': True, 'null': True}

class Client(models.Model): # хранит имя клиента рассылки и его почту
    name = models.CharField(max_length=50, verbose_name='имя клиента')
    mail = models.EmailField(max_length=50, verbose_name='email клиента')
    is_active = models.BooleanField(default=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='пользователь')

    def __str__(self):
        return f'{self.name}: {self.mail}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        ordering = ['name']


class Message(models.Model): # хранит шаблон письма
    name = models.CharField(max_length=30, verbose_name='название')
    title = models.CharField(max_length=200, **NULLABLE, verbose_name='тема письма')
    message = models.TextField(verbose_name='сообщение')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='пользователь')

    def __str__(self):
        return f'{self.name}: {self.title}'


    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        ordering = ['name']


class MailingModel(models.Model): # хранит рассылку
    WEEK_DAYS = [
        ('1', 'Monday'),
        ('2', 'Tuesday'),
        ('3', 'Wednesday'),
        ('4', 'Thursday'),
        ('5', 'Friday'),
        ('6', 'Saturday'),
        ('7', 'Sunday')
    ]
    name = models.CharField(max_length=20, verbose_name = 'название рассылки')
    time_from = models.TimeField(auto_now=False, auto_now_add=False, verbose_name='начало рассылки')
    time_to = models.TimeField(auto_now=False, auto_now_add=False, verbose_name='окончание рассылки')
    week_day = models.CharField(max_length=1, choices=WEEK_DAYS, **NULLABLE, verbose_name='день недели')
    description = models.TextField(**NULLABLE, verbose_name='описание рассылки')
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, **NULLABLE, verbose_name='текст рассылки')
    sent = models.BooleanField(default=False, verbose_name='рассылка проведена')
    is_active = models.BooleanField(default=False, verbose_name='активна')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='пользователь')

    def __str__(self):
        return f'{self.name}: weekday - {self.week_day}, time {self.time_from} - {self.time_to}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ['time_from']


class MailingList(models.Model): # хранит список рассылка-клиент
    mailing_model = models.ForeignKey(MailingModel, on_delete=models.CASCADE, verbose_name='рассылка')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='пользователь')

    def __str__(self):
        return f'{self.mailing_model}: -> {self.client}'

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'
        unique_together = ('mailing_model', 'client')


class LogList(models.Model): # лог ошибок и успехов при отправке почты
    mailing_model = models.ForeignKey(MailingModel, on_delete=models.CASCADE, **NULLABLE, verbose_name='рассылка')
    time = models.DateTimeField(default=timezone.now, verbose_name='время рассылки')
    error_type = models.CharField(max_length=50, verbose_name='успех / тип ошибки')
    error_message = models.TextField(verbose_name='успех / сообщение об ошибке')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='пользователь')

    class Meta:
        verbose_name = 'лог рассылки'
        verbose_name_plural = 'логи рассылки'
        ordering = ['-time']

mailing/forms.py
from django import forms
from django.forms import BaseFormSet

from mailing.models import MailingModel, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingModelForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingModel
        fields = ('name', 'time_from', 'time_to', 'week_day', 'description', 'message', 'is_active')

    def __init__(self, *args, **kwargs):
       user = kwargs.pop('user')
       super().__init__(*args, **kwargs)
       self.fields['message'].queryset = Message.objects.filter(owner=user)


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'mail')


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'title', 'message')

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Управление рассылками</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
</head>
<body>
<script src="{% static "js/bootstrap.bundle.min.js" %}"></script>

{% include 'mailing/includes/main_menu.html' %}

{% block content %}
{% endblock %}

{% include 'mailing/includes/footer.html' %}

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
  <div class="col-12">
    <div class="row">
      <div class="col-6">
        <div class="card">
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <p>Хотите удалить клиента {{ object.name }}?</p>
              <button type="submit" class="btn btn-danger">Подтвердить</button>
              <a href="{% url 'mailing:messages_list' %}" class="btn btn-primary">Отменить</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Список клиентов рассылки</h1>
    </div>

    <div class="container">
        <div class = "col-12 mb-5">
            <a href="{% url 'mailing:create_client' %}" class="btn btn-primary">Добавить клиента</a>
        </div>
        <div class="row text-start">
            <div class="col-lg-12 col-md-6 col-sm-12">

                    {% include 'mailing/includes/client_card.html' %}

            </div>

        </div>
        {% include 'mailing/includes/pagination.html' with page=page_obj %}
    </div>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-1 pb-md-1 mx-auto text-center">
        <h4 class="display-5">Ваша статистика</h4>
    </div>

    <div class="container">
        <div class="row text-center">


            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h5 class="my-0 font-weight-normal">
                            Всего рассылок
                        </h5>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{mailing_amount}}</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h5 class="my-0 font-weight-normal">
                            Активных рассылок
                        </h5>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{active_mailing_amount}}</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h5 class="my-0 font-weight-normal">
                            Клиентов в базе
                        </h5>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{client_amount}}</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="pricing-header px-3 py-3 pt-md-4 pb-md-4 mx-auto text-center">
        <h4 class="display-5">Наш блог</h4>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-12 col-md-6 col-sm-12">

                {% for object in object_list %}
                    {% include 'blog/includes/post_card.html' %}
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/loglist_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Тексты рассылок</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-12 col-md-6 col-sm-12">


                <div class="card">
                  <div class="card-body">
                    <table class="table table-striped">
                      <tr>
                        <th>№</th>
                        <th>Рассылка</th>
                        <th>Дата и время</th>
                        <th>Успех / тип ошибки</th>
                        <th>Успех / сообщение об ошибке</th>
                      </tr>
                      {% for object in object_list %}
                        <tr>
                          <td>{{ object.pk }}</td>
                          <td>{{ object.mailing.name }}</td>
                          <td>{{ object.time }}</td>
                          <td>{{ object.error_type }}</td>
                          <td>{{ object.error_message }}</td>
                        </tr>
                      {% endfor %}
                    </table>
                  </div>
                </div>

            </div>
        </div>
        {% include 'mailing/includes/pagination.html' with page=page_obj %}
    </div>
{% endblock %}

mailing/templates/mailing/mailinglist_form.html
{% extends 'mailing/base.html' %}
{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Сообщение</h1>
    </div>

    <div class="container">
      <div class="col-12">
          <div class="row">
              <div class="col-3"></div>
              <div class="col-6">
                  <div class="card">
                      <div class="card-body">
                          <form method="post" enctype="multipart/form-data">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button type="submit">Сохранить</button>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingmodel_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
  <div class="col-12">
    <div class="row">
      <div class="col-6">
        <div class="card">
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <p>Хотите удалить рассылку {{ object.name }}?</p>
              <button type="submit" class="btn btn-danger">Подтвердить</button>
              <a href="{% url 'mailing:mailing_list' %}" class="btn btn-primary">Отменить</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

mailing/templates/mailing/mailingmodel_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ object.name }}</h1>
    </div>

    <div class="container">
        <div class = "col-12 mb-5">
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-primary">Назад</a>
            <a href="{% url 'mailing:update_mailing' object.pk %}" class="btn btn-primary">Редактировать</a>
            <a href="{% url 'mailing:delete_mailing' object.pk %}" class="btn btn-primary">Удалить</a>
        </div>


        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Id</td>
                        <td>{{ object.pk }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Название</td>
                        <td>{{ object.name }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Начало рассылки</td>
                        <td>{{ object.time_from }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Окончание рассылки</td>
                        <td>{{ object.time_to }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">День недели</td>
                        <td>{{ object.week_day }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Описание</td>
                        <td>{{ object.description }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Сообщение</td>
                        <td>{{ object.message.message }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Активна</td>
                        <td>{{ object.is_active }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>



    <div class="container">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h5 class="display-5">Список клиентов, участвующих в рассылке</h5>
        </div>


        <div class = "col-12 mb-5">
            <a href="{% url 'mailing:redact_mailing_clients' object.pk %}" class="btn btn-primary">Редактировать</a>

        </div>



            <div class="card">
              <div class="card-body">
                <table class="table table-striped">
                  <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>email</th>
                  </tr>
                  {% for letter in object.mailinglist_set.all %}
                      <tr>
                        <td>{{ letter.pk }}</td>
                        <td>{{ letter.client.name }}</td>
                        <td>{{ letter.client.mail }}</td>
                      </tr>
                  {% endfor %}
                </table>
              </div>
            </div>



    </div>


{% endblock %}

mailing/templates/mailing/mailingmodel_form.html
{% extends 'mailing/base.html' %}
{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Рассылка</h1>
    </div>

    <div class="container">
      <div class="col-12">
          <div class="row">
              <div class="col-3"></div>
              <div class="col-6">
                  <div class="card">
                      <div class="card-body">
                          <form method="post" enctype="multipart/form-data">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button type="submit">Сохранить</button>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingmodel_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Список рассылок</h1>
    </div>

    <div class="container">
        <div class = "col-12 mb-5">
            <a href="{% url 'mailing:create_mailing' %}" class="btn btn-primary">Добавить рассылку</a>
        </div>
        <div class="row text-start">
            <div class="col-lg-12 col-md-6 col-sm-12">

                    {% include 'mailing/includes/mailing_card.html' %}

            </div>

        </div>
        {% include 'mailing/includes/pagination.html' with page=page_obj %}
    </div>
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
  <div class="col-12">
    <div class="row">
      <div class="col-6">
        <div class="card">
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <p>Хотите удалить сообщение {{ object.name }}?</p>
              <button type="submit" class="btn btn-danger">Подтвердить</button>
              <a href="{% url 'mailing:messages_list' %}" class="btn btn-primary">Отменить</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ object.name }}</h1>
    </div>

    <div class="container">
        <div class = "col-12 mb-5">
            <a href="{% url 'mailing:messages_list' %}" class="btn btn-primary">Назад</a>
        </div>
        <div class="row text-start">
            <div class="col-lg-12 col-md-6 col-sm-12">
                {% if object.title %}
                    Тема: {{ object.title }}
                {% else %}
                    Без темы
                {% endif %}

            </div>
        </div>
        <div class="row text-start">
            <div class="col-lg-12 col-md-6 col-sm-12">
                    {{ object.message }}
            </div>

        </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}
{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Сообщение</h1>
    </div>

    <div class="container">
      <div class="col-12">
          <div class="row">
              <div class="col-3"></div>
              <div class="col-6">
                  <div class="card">
                      <div class="card-body">
                          <form method="post" enctype="multipart/form-data">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button type="submit">Сохранить</button>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
{% endblock %}

mailing/templates/mailing/redact_mailing_clients.html
{% extends 'mailing/base.html' %}
{% block content %}
{% include 'mailing/includes/mailing_menu.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Список клиентов рассылки</h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-1"></div>
            <div class = "col-2 mb-5">
                <a href="{% url 'mailing:detail_mailing' pk_mailindmodel %}" class="btn btn-primary">Вернуться в рассылку</a>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <h5 align="center">Добавлены в рассылку</h5>
                <div class="card">
                  <div class="card-body">
                    <table class="table table-striped">
                      <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>email</th>
                        <th>Активен</th>
                        <th><a href="{% url 'mailing:delete_all_clients_from_mailinglist' pk_mailindmodel %}">>></a></th>
                      </tr>
                      {% for client in emails_in_mailinglist %}
                        {% include 'mailing/includes/redact_mailing_clients_card_in.html' %}
                      {% endfor %}
                    </table>
                  </div>
                </div>


            </div>

              <div class="col-lg-6 col-md-6 col-sm-12">
                <h5 align="center">Не в рассылке</h5>
                <div class="card">
                  <div class="card-body">
                    <table class="table table-striped">
                      <tr>
                        <th><a href="{% url 'mailing:add_all_clients_to_mailinglist' pk_mailindmodel %}"><<</a></th>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>email</th>
                        <th>Активен</th>

                      </tr>
                      {% for client in emails_not_in_mailinglist %}
                        {% include 'mailing/includes/redact_mailing_clients_card_out.html' %}
                      {% endfor %}
                    </table>
                  </div>
                </div>
              </div>


        </div>
    </div>
{% endblock %}