blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig
app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view_post'),
    path('create', BlogCreateView.as_view(), name='create_post'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update_post'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete_post'),

]

conf/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mailing
import users
from conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, UserUpdateView, generate_new_password, RegisterView, \
    verification_new_user, send_new_verification_code

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('profile/verification/<int:pk>', verification_new_user, name='verification_new_user'),
    path('profile/send_verification/<int:pk>', send_new_verification_code, name='send_verification'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='email')
    avatar = models.ImageField(upload_to='users/', **NULLABLE, verbose_name='аватар')
    is_active = models.BooleanField(default=False, verbose_name='пользователь верифицирован')
    verification_code = models.CharField(max_length=10, **NULLABLE, verbose_name='код верификации')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django import forms
from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class RegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class LoginViewForm(StyleFormMixin, AuthenticationForm):

    class Meta:
        model = User
        fields = ('email', 'password')


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from django.contrib.auth.base_user import BaseUserManager

from conf import settings
from users.forms import RegisterForm, LoginViewForm, UserForm
from users.models import User

class LoginView(BaseLoginView):
    template_name = 'users/login.html'
    form_class = LoginViewForm
    success_url = reverse_lazy('catalog:index')


class LogoutView(BaseLogoutView):
    pass


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def generate_new_password(request):  # отправляет на почту пользователю новый пароль
    new_password = BaseUserManager().make_random_password()
    request.user.set_password(new_password)
    request.user.save()
    send_mail(subject='Смена пароля',
              message=f'Ваш пароль на платформе Рассылки был изменён на {new_password}',
              from_email=settings.EMAIL_HOST_USER,
              recipient_list=[request.user.email])
    return redirect(reverse('users:login'))


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        self.object = form.save()
        verification_code = BaseUserManager().make_random_password()
        self.object.verification_code = verification_code
        self.object.save(update_fields=['verification_code'])
        send_mail(subject='Регистрация на платформе Рассылки',
                  message=f'Ваш код для верификации: {verification_code}',
                  from_email=settings.EMAIL_HOST_USER,
                  recipient_list=[self.object.email])
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('users:verification_new_user', args=[self.object.pk])


def verification_new_user(request, pk):  # верифицирует пользователя по коду с почты
    if request.method == 'POST':
        verification_code = request.POST.get('verification_code')
        try:
            new_user = User.objects.get(verification_code=verification_code)
        except:
            context = {
                'first_trial': False,
                'pk': pk,
            }
            return render(request, 'users/verification.html', context)
        else:
            new_user.is_active = True
            new_user.verification_code = ''
            new_user.save(update_fields=['is_active', 'verification_code'])
            login(request, new_user)  # авторизуем пользователя и отправляем на главную страницу
            return redirect(reverse('mailing:mailing_list'))
            # return redirect(reverse('users:login')) #  если не авторизовать сразу, можно отправить на авторизацию
    else:
        context = {
            'first_trial': True,
            'pk': pk
        }
        return render(request, 'users/verification.html', context)


def send_new_verification_code(request, pk):  # отправляет новый код верификации на почту
    try:
        new_user = User.objects.get(pk=pk)
        user_email = new_user.email
        verification_code = BaseUserManager().make_random_password()
        new_user.verification_code = verification_code
        new_user.save(update_fields=['verification_code'])

        send_mail(subject='Регистрация на платформе Skystore',
                  message=f'Ваш код для верификации: {verification_code}',
                  from_email=settings.EMAIL_HOST_USER,
                  recipient_list=[user_email])
        return redirect(reverse('users:verification_new_user', args=[pk]))

    except:
        return redirect(reverse('users:verification_new_user', args=[pk]))

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Вход</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/verification.html
{% extends 'mailing/base.html' %}

{% block content %}
</div>


    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        <p>
                            {% if first_trial %}
                                <label for="id_verification_code">Код верификации:</label>
                            {% else %}
                                <label for="id_verification_code">Введен неверный код верификации:</label>
                            {% endif %}
                            {% csrf_token %}
                        <input type="text" name="verification_code" maxlength="10" class="form-control" id="id_verification_code">
                        </p>
                        <button type="submit" class="btn btn-success">Отправить</button>
                        {% if not first_trial %}
                            <a href="{% url 'users:send_verification' pk %}" class="btn btn-danger">Отправить ещё раз</a>
                        {% endif %}
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}